# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'popup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for popup

pod 'BulletinBoard'

  target 'popupTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'popupUITests' do
    # Pods for testing
  end

end
